version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: instaballot
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - pg-data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  pg-data:
  redis-data: